### ISSUE TITLE
Add Safe Location

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#1068]
Many of the unseen cards need to put cards in the "safeguard" location.  It isn't completely clear how that area works, but we need that spot to transfer cards.

**Comment by micahstairs** [comment]
The location is called the "safe".
-- effects that safeguard available standard achievements, and sometimes other cards, as secrets in your safe
-- safe limit starts as 5, reduces to 1 depending on most advanced splay

What happens if your safe limit decreases and you no longer have space for an existing card?
nothing.
```
It's a soft limit - existing cards stay
If you would move a card to your Safe and it's already full, do nothing instead
Ex: "Draw and safeguard a 6", with a full safe, you draw the 6, and then fail to move it
so it stays in your hand
Or something like "Safeguard each card in your hand" - you'd do them one by one, until the limit was reached, and then ignore the rest
```
