### ISSUE TITLE
Create generalized bulk transfer function

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#1268]
We need a better way to do bulk transfers like in Fission and Parachute. I want less custom code for each card, and a single notification going to the frontend, which passes the different parameters of the bulk transfer.

**Comment by micahstairs** [comment]
There are so many cards where this feature would be useful! Marking this as high-priority.

**Comment by micahstairs** [comment]
To be clear, this mechanism would display one log message but move a lot of cards at once.

**Comment by micahstairs** [comment]
Other cards where this would be useful:
- Great Barrier Reef
- Pizza Pacaya
- Sanskrit
- Jumbo Kingdom
- Oculus Quest

**Comment by micahstairs** [comment]
We could consider adding a threshold (can be overridden by caller) which tells us when we should report each individual transfer instead of doing the bulk. E.g. if there's only 1 or 2 cards, we probably don't want to do a bulk transfer. But if it's a deck with 2 cards being junked then we might still want to just do a bulk transfer.

Maybe this is overkill though and we should keep it simple.

**Comment by micahstairs** [comment]
Oh this would probably be best implemented using the existing `transferCardFromTo` function, but we could pass a property  called `mute_notification` or something (defaulted to false but set to true for bulk notifications). Then the caller would be responsible to write their own notification as they see fit. This `transferCardFromTo` function would still pass a notification to the frontend with a delay of 0 to move the card.

**Comment by brianwk** [comment]
@micahstairs Putting a delay of zero breaks the game engine since it seems to rely on the delay due to how the frontend works. This is the cause of #1287 

For this task, the entire message sending needs to be changed to speed up those card transfers. Couldn't we just make it so one notification can list every card instead of listing it out one by one? Also we can't call updateDisplay etc in the same functions that move the cards, since this causes concurrency issues when multiple calls execute (triggered by the asynchronous subscriber)
