### ISSUE TITLE
Add Echoes hexagon icons to spritesheets

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#377]
We need the echoes hexagons to implement the expansion.

**Comment by micahstairs** [comment]
We will put these right below the Artifact icons, following the same pattern.

**Comment by micahstairs** [comment]
Actually that spritesheet is already really big and close to our limit, so we should create a new spritesheet instead of adding it to the existing one.

To make the spritesheet as small as possible, I propose that we make it 11 columns and 10 rows. There are 15 age 1 cards, so we will put the 11th-15th icons in the 11th column.
