### ISSUE TITLE
Add Cities hexagon icons to spritesheets

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#378]
What's interesting about the hexagon icons in cities is that the same image is used in an entire age, but colored differently based on the color of the card itself.

Not sure how that would be handled when extracting images, but I thought I'd point it out.  If we can have the colored parts be transparent, then we'd only need 10 icons.

**Comment by micahstairs** [comment]
Instead of trying to re-color the icons, I think it will be simplest if we add the 5x10=50 icons to the existing spritesheet. We have extra room in the 11th-15th column of the existing spreadsheet that we can cram them into (rows 2-10 and 13).

The reason for cramming them into the sheet without making it larger is because we are already close to the file size limit for BGA images.
