### ISSUE TITLE
Add special Cities icons to spritesheets

### ISSUE THREAD

**Issue by ultimatefiend** [micahstairs/bga-innovation#379]
The special icons present on the Cities cards (the plus, arrows, flag and fountain) are needed when rendering cards.

**Comment by micahstairs** [comment]
We need each of these symbols in each of the 5 colors. As always, please use ImageMagick to make this spritesheet!

**Comment by micahstairs** [comment]
Thanks Josh! I think the only thing that's missing is that we don't have a way right now to render the resource icons appearing under the search icon since the border is a bit different. The border is the same as the other Cities icons though. Do you have a suggestion for the best way to tackle this?

**Comment by normaljosh** [comment]
I made another mask that includes both the border and the search icons in PR #418 , would this work?

**Comment by micahstairs** [comment]
Yes, I think this will work great! I really appreciate the effort you've put into this.
