### ISSUE TITLE
Count maximum nested effects

### ISSUE THREAD

**Issue by micahstairs** [micahstairs/bga-innovation#43]
Due to the way that nested effects are implemented, we need to know what the upper bound of nested effects are. For example, Self Service and Software are two examples of card which can have a nested effect, since they instruct you to execute the effects on another card.

- Which cards in the base set can trigger nested effects?
- Which cards in the Artifacts expansion can trigger nested effects?

To make it easier to confirm we aren't missing any cards, please list the names of the cards and not just give me a number.

**NOTE:** Before you begin working on this, please **assign this issue to yourself**. If you do not do this, then there's the possibility that 2 people will end up doing the same task, which is not a good use of time.

**Comment by jacksonmead** [comment]
@micahstairs Is there something else I need to do with this? Or will this comment with the info just sit here until it's needed (i.e., when the programming of the expansions is happening)?

**Comment by micahstairs** [comment]
Sorry I forgot to respond to this! Thanks for looking through the cards, this is helpful. I'll close this issue.

**Comment by jacksonmead** [comment]
Doing some noodling around to see what the theoretical maximum is (feel free to ignore this).

Garland's Ruby Slippers (Artifacts, Age 8) has you meld an 8 from your hand and do its effects. And since it's coming from your hand, you wouldn't go up to a 9 or a 10 like you would if you were drawing, so you would definitely be melding an 8 (if anything). However, since none of the other cards with nested effects are Age 8, this is also a dead end (like Rover Curiosity), so I think we can go down from a theoretical 21 cards to a maximum theoretical of 20.

Sunshu Ao (Figures, Age 1) is another dead end. Its nested effect is due to a karma, "if you would tuck a yellow card, instead excute" its effects. However, there are no other yellow nested effects cards. So we're down to a theoretical maximum of 19.

Heh, just discovered a little loop effect. For cards where you are not drawing and then melding, i.e., where you are executing the effect of a card that is on someone's board, it's possible to loop back to a card that's already part of the nesting stack. For example, if you meld and do the effects of Roundhay Garden Scene (Artifacts, Age 7) due to the effects of some other card, you could then meld, say, Priest-King (Artifacts, Age 1), which has you score a card from your hand and then execute your top card of that color. So if you score a purple card, then you go back to doing the effects of Roundhay Garden Scene again. So essentially, cards like Priest-King and Charter of Liberties (Artifacts. Age 3) let you loop back around.to somewhere else in the stack. So it may very well be possible to have 21 or more cards on the stack, and, as I said in my first comment on this issue, that's not even counting normal karma effects, where I assume you'd have to add the Figures card with the karma onto the stack. Of course, a lot of these cards might be melded on top of each other, and it's probably not possible to have all the required top cards to make a full chain happen. So, all that to say, it might be a very hard problem to calculate the theoretical maximum, and it sounds like the solution in #45 is definitely the way to go. Thanks for letting me engage in my noodling.

**Comment by micahstairs** [comment]
@jacksonmead Thanks for digging into that a bit more! I hadn't even considered a loop like the one you described. I agree this makes it very hard to establish an upper bound. I'll definitely move forward with #45 then.
