### ISSUE TITLE
Karaoke + Satellites throws an error

### ISSUE THREAD

**Issue by madisonsilver** [micahstairs/bga-innovation#831]
Melding and executing Karaoke with Satellites' dogma throws an error: `Unexpected error: Error while processing database request`
See game https://boardgamearena.com/table?table=326278397 move ~210.

**Comment by micahstairs** [comment]
[98.33.10.237] [91718562/MadisonSilver] Error (1064) while processing SQL request: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 - Request: SELECT * FROM card WHERE id = 
13/12 18:45:28 [error] [T326278397] [98.33.10.237] [91718562/MadisonSilver] Unexpected exception: Error while processing SQL request (Localhost via UNIX socket): SELECT * FROM card WHERE id = 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 (BGA service error 1670953528)
#0 /var/tournoi/release/tournoi-221205-1000-gs/www/include/APP_DbObject.inc.php(643): APP_DbObject::DbQuery()
#1 /var/tournoi/release/tournoi-221205-1000-gs/www/include/APP_DbObject.inc.php(668): APP_DbObject->getObjectFromDB()
#2 /var/tournoi/release/games/innovationalpha/221212-0052/innovationalpha.game.php(3735): APP_DbObject->getNonEmptyObjectFromDB()
#3 /var/tournoi/release/games/innovationalpha/221212-0052/innovationalpha.game.php(14180): innovationalpha->getCardInfo()
#4 /var/tournoi/release/tournoi-221205-1000-gs/www/game/module/table/gamestate.game.php(502): innovationalpha->stPlayerInvolvedTurn()
#5 /var/tournoi/release/tournoi-221205-1000-gs/www/game/module/table/gamestate.game.php(398): Gamestate->jumpToState()
#6 /var/tournoi/release/games/innovationalpha/221212-0052/innovationalpha.game.php(9355): Gamestate->nextState()
#7 /var/tournoi/release/tournoi-221205-1000-gs/www/game/module/table/gamestate.game.php(502): innovationalpha->stDogmaEffect()
#8 /var/tournoi/release/tournoi-221205-1000-gs/www/game/module/table/gamestate.game.php(398): Gamestate->jumpToState()
#9 /var/tournoi/release/games/innovationalpha/221212-0052/innovationalpha.game.php(14367): Gamestate->nextState()
#10 /var/tournoi/release/tournoi-221205-1000-gs/www/game/module/table/gamestate.game.php(502): innovationalpha->stInterPlayerInvolvedTurn()
#11 /var/tournoi/release/tournoi-221205-1000-gs/www/game/module/table/gamestate.game.php(398): Gamestate->jumpToState()
#12 /var/tournoi/release/games/innovationalpha/221212-0052/innovationalpha.game.php(24009): Gamestate->nextState()
#13 /var/tournoi/release/tournoi-221205-1000-gs/www/game/module/table/gamestate.game.php(502): innovationalpha->stInterInteractionStep()
#14 /var/tournoi/release/tournoi-221205-1000-gs/www/game/module/table/gamestate.game.php(398): Gamestate->jumpToState()
#15 /var/tournoi/release/games/innovationalpha/221212-0052/innovationalpha.game.php(25295): Gamestate->nextState()
#16 /var/tournoi/release/tournoi-221205-1000-gs/www/game/module/table/gamestate.game.php(502): innovationalpha->stInterSelectionMove()
#17 /var/tournoi/release/tournoi-221205-1000-gs/www/game/module/table/gamestate.game.php(398): Gamestate->jumpToState()
#18 /var/tournoi/release/games/innovationalpha/221212-0052/innovationalpha.game.php(7405): Gamestate->nextState()
#19 /var/tournoi/release/games/innovationalpha/221212-0052/innovationalpha.action.php(283): innovationalpha->choose()
#20 /var/tournoi/release/tournoi-221205-1000-gs/www/include/webActionCore.inc.php(189): action_innovationalpha->choose()
#21 /var/tournoi/release/tournoi-221205-1000-gs/www/index.php(265): launchWebAction()
#22 {main}

**Comment by micahstairs** [comment]
Good news! I replicated this in the studio.

**Comment by micahstairs** [comment]
Ah so the problem here is that the Echo effect never got the chance to be executed, since only the non-demand effects were triggered.

More generally, there are a few other cards which could also be affected by a similar bug:
- Charitable Trust: "You may meld the card you drew due to Charitable Trust's echo effect"
- Stethoscope: "If you melded a blue card due to Stethoscope's echo effect"
- Dentures: "Score the top two non-bottom cards of the color of the last card you tucked due to Dentures"
- Jet: "I demand you return your top card of the color I melded due to Jet's echo effect!"

And if we extend this search beyond Echo effects, we should also double-check:
- Oars: "If no cards were transferred due to this demand, draw a 1"
- Mapmaking: "If any card was transferred due to the demand, draw and score a 1"
- Gunpowder: "If any card was transfered due to the demand, draw and score a 2"
- The Pirate Code: "If any card was transferred due to the demand, score the lowest top card with a coin from your board"

In practice, it's likely that many of these bugs are unreachable (due to the fact that only higher aged cards tend to trigger nested execution, however, it's worth firming up each of these implementations anyway.
